### ISSUE TITLE
分流下载速度变为0，疑似存在内存溢出，内存不回收情况

### ISSUE THREAD

**Issue by wanyulaowang** [StarCitizenToolBox/app#65]
现象：使用盒子分流下载，每次下载约5GB时会出现速度降为0
分析：观察任务管理器，发现“桌面窗口管理器”内存占用过大（占用约为5G），关闭盒子进程后，内存断崖式减少，并且重启盒子应用后，重启下载任务，速度恢复正常
参考复现流程：
1.启动盒子
2.新建或继续P4K下载任务
3.待下载速度变为0时，可打开任务管理器，查看“桌面窗口管理器”进程的内存占用
4.关闭盒子应用程序，可打开任务管理器，查看“桌面窗口管理器”进程的内存占用（内存会下降很多）
5.重新打开盒子应用，继续下载任务，发现校验后继续下载速度恢复

个人认为应该是内存溢出和垃圾空间未回收导致的内存异常占用，望大大们排查一下

**Comment by xkeyC** [comment]
你的显卡驱动漏了，和下载进程无关，盒子使用了一些 gpu api 绘制 UI，你开着盒子也会漏，检查显卡驱动是否有更新

**Comment by xkeyC** [comment]
系统更新也可以检查一下
